### ISSUE TITLE
[Bug] The exporter is not working

### ISSUE THREAD

**Issue by ngosang** [PhilipMay/smart-prom-next#41]
I'm using a custom build of https://github.com/matusnovak/prometheus-smartctl with the changes from several issues/prs opened in that project.
I just tested your fork as a drop-in replacement but it didn't work. Maybe you can apply similar patches and I will test it again.

* Original code => https://github.com/matusnovak/prometheus-smartctl/blob/master/smartprom.py
* My changes => [smartprom.py.txt](https://github.com/PhilipMay/smart-prom-next/files/9202569/smartprom.py.txt)
* Log traces when I run your Docker image => [_smartctl-exporter_logs.txt](https://github.com/PhilipMay/smart-prom-next/files/9202577/_smartctl-exporter_logs.txt)

**Comment by PhilipMay** [comment]
Hi @ngosang 

why exactly do you think that the exporter is not working?
Can you please provide more details?

What do you expect to happen? What did happen / did not happen?

Do you see metrics described here?
https://github.com/PhilipMay/smart-prom-next#available-metrics

The `_smartctl-exporter_logs.txt` you linked contains "warnings":

```
Calling ['smartctl', '--xall', '--json', '/dev/sda'] resturned non zero returncode! returncode: 4 stderr: 'not set'
Calling ['smartctl', '--xall', '--json', '/dev/sdb'] resturned non zero returncode! returncode: 4 stderr: 'not set'
Calling ['smartctl', '--xall', '--json', '/dev/sdc'] resturned non zero returncode! returncode: 4 stderr: 'not set'
Calling ['smartctl', '--xall', '--json', '/dev/sda'] resturned non zero returncode! returncode: 4 stderr: 'not set'
Calling ['smartctl', '--xall', '--json', '/dev/sdb'] resturned non zero returncode! returncode: 4 stderr: 'not set'
Calling ['smartctl', '--xall', '--json', '/dev/sdc'] resturned non zero returncode! returncode: 4 stderr: 'not set'
```

But they are ok. smartctl can return a non `0` exit code and still work. From the output I can see this in the log:

```
    "argv": [
      "smartctl",
      "--xall",
      "--json",
      "/dev/sda"
    ],
    "messages": [
      {
        "string": "Warning: This result is based on an Attribute check.",
        "severity": "warning"
      }
    ],
    "exit_status": 4
  },
```

That is not an error.

**Comment by PhilipMay** [comment]
Exit status 4 means bit 2 is set which means:

> Some SMART or other ATA command to the disk failed, or there was a checksum error in a SMART data structure (see '-b' option above).

See "EXIT STATUS" from here: https://www.smartmontools.org/browser/trunk/smartmontools/smartctl.8.in

Is it possible that you did not set `    privileged: true`?

**Comment by PhilipMay** [comment]
But in the json file from the logs I can see all relevant info that is needed. So smart-prom-next should be able to crape what it gets.
Even if non zero is returned.

**Comment by ngosang** [comment]
You are right, the exporter is working and I can see the metrics. You can close this issue.
As I said in https://github.com/matusnovak/prometheus-smartctl/issues/19#issuecomment-1197347681, I'm not going to use this exporter for now but I can give you some advice:

* The exporter should be silent by default (only error traces). You can make log level configurable but at the default INFO level should be quite. I have a centralized log solution and I prefer to not have to filter traces.
* There are too many metrics, maybe add some Env Vars to make them optional?
* The CPU usage is greater than https://github.com/matusnovak/prometheus-smartctl/ Maybe you can improve that or make refresh interval configurable.
![image](https://user-images.githubusercontent.com/10577978/181371823-35a79e50-73ee-44b6-aee5-f14e0a9547ae.png)

**Comment by PhilipMay** [comment]
Many thanks @ngosang for retesting and your comments.

> There are too many metrics, maybe add some Env Vars to make them optional?

Can you tell me which metrics would you make optional? Which do you think are "too many"?

> The CPU usage is greater than https://github.com/matusnovak/prometheus-smartctl/ Maybe you can improve that or make refresh interval configurable.

My refresh interval default is at 60s. The one of `matusnovak/prometheus-smartctl` is at 20s. Do you have an idea why my CPU time is so much higher?

- the refresh interval is configurable with `SMART_INFO_READ_INTERVAL_SECONDS`. see here: https://github.com/PhilipMay/smart-prom-next#configuration-options--environment-variables

**Comment by ngosang** [comment]
> My refresh interval default is at 60s. The one of matusnovak/prometheus-smartctl is at 20s. Do you have an idea why my CPU time is so much higher?

I'm using 600 in my fork.

**Comment by PhilipMay** [comment]
> I'm using 600 in my fork.

That might be the explanation...

**Comment by PhilipMay** [comment]
closing since this is no bug
