### ISSUE TITLE
reduce Alpine image size

### ISSUE THREAD

**Issue by PhilipMay** [PhilipMay/smart-prom-next#45]
@ngosang sais: 

> it's possible to reduce Docker' images size to half. (if you do some changes in the Dockerfiles to avoid caching files and reduce the number of layers)

> You can open another issue for that.

So - this is the issue - can yo provide some hints @ngosang ?

**Comment by ngosang** [comment]
Hint => https://github.com/matusnovak/prometheus-smartctl/pull/31/files

You can use this tool to inspect the layers => https://github.com/wagoodman/dive

**Comment by ngosang** [comment]
Image name: ghcr.io/philipmay/smart-prom-next:0.0.4rc1-alpine
Total Image size: 71 MB 
Potential wasted space: 14 MB
Image efficiency score: 89 %  

Image name: matusnovak/prometheus-smartctl:v2.0.0 
Total Image size: 52 MB
Potential wasted space: 735 kB
Image efficiency score: 99 %

**Comment by PhilipMay** [comment]
done with Alpine - what else can be done with Alpine and / or Debian?

**Comment by ngosang** [comment]
Sorry, I don't have time to explain. You can reduce both Docker images even more as enhancement. You can close if you want.

**Comment by PhilipMay** [comment]
https://www.fromlatest.io/

**Comment by PhilipMay** [comment]
https://www.augmentedmind.de/2022/02/06/optimize-docker-image-size/

**Comment by PhilipMay** [comment]
```
alpine defult
70.7

rm -rf /root/.cache/
kein effekt

rm -rf /var/cache/apk/*
68.2MB
```

**Comment by PhilipMay** [comment]
done
